### ISSUE TITLE
Error after encapsulate the passport routes

### ISSUE THREAD

**Issue by benvindo** [sfelix-martins/passport-multiauth#1]
Hi, after add code  above:

```
Passport::routes();

        Route::group(['middleware' => 'custom-provider'], function () {
            Passport::routes(function ($router) {
                return $router->forAccessTokens();
            });
        });`
```
At the terminal show me this error, when try execute any command:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'App\Providers\Route' not found 
```

**Comment by sfelix-martins** [comment]
@benvindo I see that you solve the problem... I think that you just don't use `Route`. You can contribute improvements in the README so that these errors do not happen again. I hope that this package help you.

Regards, Samuel

**Comment by iCrashed** [comment]
I am still getting this error. How did you solve @benvindo. 
@sfelix-martins I shouldn't use Route?
