### ISSUE TITLE
Get all of the access tokens for the user relating with Provider.

### ISSUE THREAD

**Issue by reymondkao** [sfelix-martins/passport-multiauth#101]
use Laravel\Passport\Passport;

trait HasMultiAuthApiTokens
    /**
     * Get all of the access tokens for the user relating with Provider.
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function tokens()
    {
        return $this->hasMany(Passport::tokenModel(), 'user_id')
            ->join('oauth_access_token_providers', function ($join) {
                $join->on(
                    'oauth_access_tokens.id', '=', 'oauth_access_token_id'
                )->where('oauth_access_token_providers.provider', '=', AuthConfigHelper::getUserProvider($this));
            })->orderBy('created_at', 'desc')
            ->select('oauth_access_tokens.*')
            ->get();
    }
}

{"result":"error","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.oauth_access_tokens' doesn't exist (SQL: select `oauth_access_tokens`.* from `oauth_access_tokens` inner join `oauth_access_token_providers` on `oauth_access_tokens`.`id` = `oauth_access_token_id` and `oauth_access_token_providers`.`provider` = customers where `oauth_access_tokens`.`user_id` = 21 and `oauth_access_tokens`.`user_id` is not null order by `created_at` desc)"}

**Comment by sfelix-martins** [comment]
@reymondkao 
Please, what’s the package, laravel and laravel passport versions?
Are you sure that migrate all packages tables?

**Comment by reymondkao** [comment]
"require": {
    "laravel/framework": "5.8.*",
    "laravel/passport": "^7.4",
    "smartins/passport-multiauth": "^4.1"
}
I have executed migrate
user account and token in different database
Passport::tokenModel() fix the error

**Comment by sfelix-martins** [comment]
@reymondkao Thanks. If you need I am available
