### ISSUE TITLE
provider validate error can response json format

### ISSUE THREAD

**Issue by reymondkao** [sfelix-martins/passport-multiauth#102]
How to setup provider validate error can response json format.
please, I need

500Internal Server Error

The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.

**Comment by sfelix-martins** [comment]
Make sure you are passing the parameter `provider` like explained [here](https://github.com/sfelix-martins/passport-multiauth#usage)

**Comment by reymondkao** [comment]
Thank you~ I understand, but others people don't know

{
    "username":"user@domain.com",
    "password":"password",
    "grant_type" : "password",
    "client_id": "client-id",
    "client_secret" : "client-secret",
    "provider" : "admins"
}

Only the provider parameter response to 500

AddCustomProvider class can add try throw 

try {

} catch (OAuthServerException $e) {
    throw new AuthenticationException;
}

please, I need... need

**Comment by sfelix-martins** [comment]
Please, send a pull request to be checked. For now you can fork the project and use from your fork.
More instructions [here](https://stackoverflow.com/a/13500676/7491725).
