### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'api_token'

### ISSUE THREAD

**Issue by SachinBahukhandi** [sfelix-martins/passport-multiauth#105]
Hi there, 
I am facing this strange issue recently. I used this library earlier for a different project and didn't encounter this issue. Moreover the issue is that in the last project I didn't have an **api_token** column.
This is the issue:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'api_token' in 'where clause' (SQL: select * from `users` where `api_token` =   **`MYTOKEN`**

**Comment by sfelix-martins** [comment]
Hi @SachinBahukhandi 

I'm sorry, but I think that it isn't related with the package.
