### ISSUE TITLE
Laravel 6?

### ISSUE THREAD

**Issue by lucasbraintly** [sfelix-martins/passport-multiauth#106]
Passport multiauth works with Laravel 6? It will be updated?

**Comment by petar-ceho** [comment]
Does it work with Laravel 6 ?

**Comment by bkintanar** [comment]
I just tried it and it doesn't support passport 8 which is what laravel 6 requires.

**Comment by moell-peng** [comment]
Will the project also maintain updates?

**Comment by sfelix-martins** [comment]
I’m sorry. I’m with difficulties to update the package frequently. 😓Please, would anyone like to help me? If yes, contact me here or by email! Thanks 😬

**Comment by sfelix-martins** [comment]
Hi!

Can you test the new branch [6.x](https://github.com/sfelix-martins/passport-multiauth/tree/6.x) changes?

Just run to install:

```sh
composer require smartins/passport-multiauth:6.x-dev
```

and follow this [README](https://github.com/sfelix-martins/passport-multiauth/blob/6.x/README.md).

If all works fine let me know!

Please, if occur any problem, let me know too! 😬

**Comment by moell-peng** [comment]
#110 Initial test, no big problems, need to provide an automatic registration provider

**Comment by sfelix-martins** [comment]
@moell-peng thanks for your contribution!

In the [commit](https://github.com/sfelix-martins/passport-multiauth/commit/6c1f3d2e8d7bc3e83acd38d968519cf53d8da658) was changed the provider registration to register package provider before laravel passport provider. Does this behavior continues?

#110

**Comment by shafrazlk** [comment]
Hi, 

Am getting below error when trying to access /auth/token with additional guards (but works fine with '**users**'.

`{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
    "hint": "",
    "message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}`

below is the requests

`username:dortha72@example.com
password:welcome1
grant_type:secret
client_id:2
client_secret:PRuAAz4G8KKioqeiStPshfWxShpEVPN2zS4McCxMy
provider:customers`

config/auth.php

[auth.zip](https://github.com/sfelix-martins/passport-multiauth/files/3850004/auth.zip)



App environment
`
"php": ">=7.2.0",
        "laravel/framework": "6.2",
        "laravel/passport": "8.x",
        "laravel/tinker": "~1.0",
        "smartins/passport-multiauth": "6.x-dev"
`

**Comment by sfelix-martins** [comment]
Hi @shafrazlk 

Try use grant type `password` instead of `secret`.

**Comment by shafrazlk** [comment]
Hi @sfelix-martins 

Sorry for the late reply.

i get the same error with below request as well

`username:dortha72@example.com
password:welcome1
grant_type:password
client_id:2
client_secret:PRuAAz4G8KKioqeiStPshfWxShpEVPN2zS4McCxMy
provider:customers`

**Comment by cch504** [comment]
> Hi @shafrazlk
> 
> Try use grant type `password` instead of `secret`.

This is working for me

**Comment by shezy26** [comment]
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_access_token_providers' already exists (SQL: create table `oauth_access_token_providers` (`oauth_access_token_id` varchar
(100) not null, `provider` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

This is error after php artisan migrate

**Comment by shezy26** [comment]
I am getting this error

League\OAuth2\Server\Exception\OAuthServerException: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. in file C:\xampp\htdocs\broadway\vendor\league\oauth2-server\src\Exception\OAuthServerException.php on line 142

**Comment by joshhornby** [comment]
I to get the following error when using `grant_type` password:

```
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
    "hint": "",
    "message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}
```

**Comment by juhasev** [comment]
Just installed on Laravel 6.5 and it looks like Client Credentials -grant works perfectly with a new custom provider! I will be also setting password grant authentication little bit later. This very promising!

**Comment by sfelix-martins** [comment]
Added support in new [release](https://github.com/sfelix-martins/passport-multiauth/releases/tag/v6.0.0)

**Comment by juhasev** [comment]
For folks who are having problems with the authentication. I would recommending reading the Laravel Passport documentation in its entirely [https://laravel.com/docs/5.8/passport](https://laravel.com/docs/5.8/passport). The docs are thin in some parts but know that Passport uses League OAuth package underneath.[https://oauth2.thephpleague.com/](https://oauth2.thephpleague.com/)
