### ISSUE TITLE
problem when token is revoked or not valid Action

### ISSUE THREAD

**Issue by Mirosine** [sfelix-martins/passport-multiauth#107]
Hi it works for me properly but when the token is incorrct or revoked  the response is the laravel native login page I want to change that and make a json response .

I'm using middlewares like this :
Route::group(['middleware' => ['api', 'multiauth:customer']], function () { ...
Route::group(['middleware' => ['api', 'multiauth:admin']], function () { ...
already thanks for any help !

**Comment by sfelix-martins** [comment]
Hi @Mirosine , Thanks!

Just pass the header `Accept` with value `application/json` in your request headers.

I hope it helps.
