### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by Daniyal-Javani** [sfelix-martins/passport-multiauth#108]
I got this error:
``
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'b358b59a4b98d6a813d733f09aaaa72fa89658b7445ffdb1fa013d78b8a4ea0d' for key 'PRIMARY' (SQL: insert into `oauth_access_token_providers` (`oauth_access_token_id`, `provider`, `created_at`, `updated_at`) values (b358b59a4b98d6a813d733f09aaaa72fa89658b7445ffdb1fa013d78b8a4ea0da97cad5660959e3e, admins, 2019-11-05 09:37:46, 2019-11-05 09:37:46))
``
I'm using `v5.8.32`
Did I missed something?

**Comment by sfelix-martins** [comment]
Hi @Daniyal-Javani , 

Thanks for your issue!

Can you give me more details how to simulate the error?
