### ISSUE TITLE
Its giving me this error on laravel 6

### ISSUE THREAD

**Issue by shezy26** [sfelix-martins/passport-multiauth#116]
League\OAuth2\Server\Exception\OAuthServerException: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. in file C:\xampp\htdocs\broadway\vendor\league\oauth2-server\src\Exception\OAuthServerException.php on line 142

**Comment by sfelix-martins** [comment]
@shezy26 please, check if the parameter `provider` is being passed.

If the error persists send more details about your project configuration.

**Comment by ismaelmartinezc** [comment]
@sfelix-martins i having this error too.
I'm passing provider parameter in request. How can I check if it had passed?

**Comment by ismaelmartinezc** [comment]
@sfelix-martins I was looking for this error.
I added "guard" instead of "provider" so I received same error than @shezy26. I replace provider "api" for "users" and all is working now.

**Comment by sfelix-martins** [comment]
@shezy26 Can you check if you have the same problem? You must pass a `provider` instead of a `guard`.
