### ISSUE TITLE
Support for Passport 8.0

### ISSUE THREAD

**Issue by stevelacey** [sfelix-martins/passport-multiauth#117]
Passport 8.0 isn't include in the composer.json yet – are there any problems it causes holding this back?

**Comment by sfelix-martins** [comment]
@stevelacey 
Thanks for you issue.

I don't mapped it. I'll check it ASAP. 

I pull request are welcome.

**Comment by juhasev** [comment]
Using the dev version is Passport 8 is working fine!

**Comment by sfelix-martins** [comment]
Support added on branch 6.x-dev. It'll be added in the next release.
