### ISSUE TITLE
choose the provider SMartins\PassportMultiauth\Providers\MultiauthServiceProvider

### ISSUE THREAD

**Issue by johnef** [sfelix-martins/passport-multiauth#13]
Hi I stack here please help
on this point you said `choose the provider SMartins\PassportMultiauth\Providers\MultiauthServiceProvider`
What do you mean choose the provider

**Comment by sfelix-martins** [comment]
Hi @johnef. In latest versions of Laravel when you run `php artisan vendor:publish` command all providers available are shown. You should choose `SMartins\PassportMultiauth\Providers\MultiauthServiceProvider`.

You can run too:
 ```
php artisan vendor:publish --provider="SMartins\PassportMultiauth\Providers\MultiauthServiceProvider"
```

**Comment by johnef** [comment]
@sfelix-martins thanks for the replay I am using Laravel 5.4, 
When I run `php artisan vendor:publish --provider="SMartins\PassportMultiauth\Providers\MultiauthServiceProvider"` I got the `vendor\smartins\passport-multiauth\database\migrations` copied to my migration folder which I did migrate and everything was OK with this step but what to do with the providers here? 

and then comes to the part Add the provider parameter in your request at `/oauth/token` I can't understand this part too.

I made all the steps you mention and try to test on postman but from where can I get the `client_id` and `client_secret` sorry I am new to this passport and laravel APIs can you please guide me here

**Comment by sfelix-martins** [comment]
@johnef 
1. Any packages has migrations, config files, translations, views and you can publish this files to see, edit, etc. In my package the command just publish a migration file. But it's not required to package works. 
2. On [laravel passport installation](https://laravel.com/docs/5.6/passport#installation) you need to run `php artisan passport:install` to create the encryption keys needed to generate secure access tokens. You should to use the `client_id` and `client_secret` from "password grant" shown by command output.
3. After install Laravel Passport, on standard use, to create an access token you should send a POST to `/oauth/token` route passing `client_id` and `client_secret` (Generated on php artisan passport:install), `grant_type`, `username` and `password`. To use my package correctly you need add to `oauth/token` request the parameter `provider` passing the any provider defined on `config/auth.php` providers array.
Example:

In your `config/auth.php` providers array you add a new provider `admins`:

```php
return [
    ...

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        // ** New provider**
        'admins' => [
            'driver' => 'eloquent',
            'model' => App\Administrator::class,
        ],
    ],
];
```

In your request parameters should looks like:

```
// The username and password of any admin created in your API
username: "user@domain.com" 
password: "password"
// The grant_type with value `password`
grant_type: "password"
// The client_id and client_secret generated by `php artisan passport:install` command
client_id: "client-id"
client_secret: "client-secret"
// Any provider defined previously
provider: "admins"
```

The package instructions assumes that the package user already has a previously knowledge in Laravel Passport. I will improve it to make the experience easier.

I hope it helps, Thanks!

**Comment by johnef** [comment]
@sfelix-martins thanks really for your effort but I try all the steps you just said but when test on postman I get always `"error": "Unauthenticated."`

**Comment by johnef** [comment]
@sfelix-martins  one more question I see this in the `vendor\smartins\passport-multiauth\src\Http\Middleware\AddCustomProvider.php` dose it should be published in my `Middleware` because I see my Middleware is same same even after installing the package.

**Comment by sfelix-martins** [comment]
The middleware don’t need to be published to your middlewares. You need just use the middleware. Please, list all steps that you follow to install and configure the package on your project.
