### ISSUE TITLE
how to authenticate  a user using username only

### ISSUE THREAD

**Issue by yassir1994** [sfelix-martins/passport-multiauth#14]
i have a type of users that have an email acting as username, and there is no password field, so how i can get access_token for this type of users
`    $http = new \GuzzleHttp\Client();

    $response = $http->post(url('oauth/token'), [
        'form_params' => [
            'grant_type' => 'password',
            'client_id' => env("PASSPORT_KEY"),
            'client_secret' => env("PASSPORT_SECRET"),
            'username' => $email,
            "provider" => "users"
        ],
    ]);

    return json_decode($response->getBody());`

**Comment by sfelix-martins** [comment]
Hello @yassir1994 , in this case I think that you should to use [personal access tokens](https://laravel.com/docs/5.6/passport#personal-access-tokens).
