### ISSUE TITLE
Keep looking inside Users table when using the middleware

### ISSUE THREAD

**Issue by wysentanu** [sfelix-martins/passport-multiauth#16]
Hi Samuel,

currently I'm using your package to implement multi-auth passport. When I am using the middleware on my route like this:

```
Route::group(['middleware' => 'auth:customer'], function () {
    Route::get('foo', function () {
        return Auth::guard('customer')->user();
    });
});
```

It returns error:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vaff.users' doesn't exist (SQL: select * from `users` where `id` = 1 limit 1)`

**_note: I'm not using Users table in my project._**

I've already configured the providers and the guards.

guards:
```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],

        'customer' => [
            'driver' => 'passport',
            'provider' => 'customers',
        ],
    ],
```

provider:
```
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'customers' => [
            'driver' => 'eloquent',
            'model' => App\Models\Customer::class,
        ],
    ],
```

If I am not using the middleware, it can returns the customer model normally.

**Comment by sfelix-martins** [comment]
Hi @wysentanu 

Thank for your issue. I'm checking...

**Comment by wysentanu** [comment]
Hi Samuel,

thanks for the reply, I already put the provider `parameter` with value `customers`, but the issue still persists.

**Comment by sfelix-martins** [comment]
@wysentanu I will test more a bit to solve this problem ASAP. A pull request would be welcome :grin:

**Comment by sfelix-martins** [comment]
@wysentanu I think I have a solution for your issue!

Firstly, the package presumes that all tables and models on providers was configured and working. If you aren't using the `users` table and `User` model please remove from providers.

The laravel passport needs of `api` guard on your core. Then you should replace the `users` provider on `api` guard config to another provider as `customers`.

E.g.:
- On your `config/auth`:
```php
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'customers',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'customers',
        ],

        'admin' => [
            'driver' => 'passport',
            'provider' => 'admins',
        ],
    ],

    'providers' => [        
        'customers' => [
            'driver' => 'eloquent',
            'model' => App\Customer::class,
        ],

        'admins' => [
            'driver' => 'eloquent',
            'model' => App\Admin::class,
        ],
    ],
```

Routes:

```
// The `customers` will replace the `users` on `api` guard
Route::middleware('auth:api')->get('/customer', function (Request $request) {
    return $request->user();
});

// Another models will work normally
Route::middleware('auth:admin')->get('/admin', function (Request $request) {
    return $request->user('admin');
});
```

On my tests it's works fine! I hope it helps.

**Comment by sfelix-martins** [comment]
@wysentanu if it is still necessary to reopen the issue.
