### ISSUE TITLE
Looking for the first provider in case of two guards

### ISSUE THREAD

**Issue by mkconsultpm** [sfelix-martins/passport-multiauth#17]
Hi.
The package is working perfectly, but I have an issue when using more than one guard:

If I use a token generated for a User **that has the same id** as an Admin,

`Route::group(['middleware' => ['api', 'auth:admin,api']], function () {
    Route::get('/admin', function ($request) {
        return $request->user();
    });
});`

This returns the Admin instance.

**Comment by sfelix-martins** [comment]
Hello @mkconsultpm ,

Thanks for your issue!

To use more than one guard you should pass the guard `api` to `$request->user()` method. E.g.: `$request->user('api')`. Or `Auth::guard('api')->user()`;

The Laravel\Passport just uses the provider from `api` guard. When new token is generated the package associate this token with the provider passed on `provider` parameter of request to create new token (POST - oauth/token). When you try request the user using an access token, the package get the provider associated with this token and set the correct provider on `auth.guards.api.provider`. Therefore to use twice or more guards you should pass the `api` guard to user. If you are trying get from default provider (users) you can call `$request->user()` method without problems. If you are trying get from another provider, e.g. `admins`, you should specify the guard. e.g.: `$request->user('admin')`;

Please, test this and give me a feedback.

Regards, Samuel Martins

**Comment by sfelix-martins** [comment]
You should make something like this:

```php
Route::group(['middleware' => ['api', 'auth:admin,api']], function () { 
    Route::get('/some_route', function ($request) {
        $user = $request->user('api');
        if ($user instanceof Admin) {
            do_something();
        } else {
            // instanceof User
            do_another_thing();
        }
    }); 
});
```

**Comment by mkconsultpm** [comment]
I think this won't be enough since `$request->user('api')` will always return a `User` instance.
Same for `$request->user('admin')` will return an `Admin`.

**Comment by sfelix-martins** [comment]
@mkconsultpm When you are using more than one guard `$request->user('api')` can returns a `User` or `Admin` instance in your case, according to generated access token. Please, test it. If there is a different behavior the package has a bug. I count on you. Thanks bro.

**Comment by odupont** [comment]
I have the same issue using same route and controller for differents auth providers (users or admins).

I fixed it replacing Authenticate middleware : the original Authenticate checks if user is logged on all available middlewares for the route. I want it to check only on the guard associated to my access token, if it's in route availables guards.

Here's the code of my **App\Http\Middleware\MultiProviderAuthenticate.php** :

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Contracts\Auth\Factory as Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use League\OAuth2\Server\Exception\OAuthServerException;
use League\OAuth2\Server\ResourceServer;
use SMartins\PassportMultiauth\Guards\GuardChecker;
use SMartins\PassportMultiauth\ProviderRepository;
use Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory;

class MultiProviderAuthenticate
{
    /**
     * The authentication factory instance.
     *
     * @var \Illuminate\Contracts\Auth\Factory
     */
    protected $auth;
    /**
     * The application instance.
     *
     * @var \Illuminate\Foundation\Application
     */
    private $app;

    /**
     * @var \League\OAuth2\Server\ResourceServer
     */
    private $server;

    /**
     * @var \SMartins\PassportMultiauth\ProviderRepository
     */
    private $providers;

    public function __construct(ResourceServer $server, ProviderRepository $providers, App $app, Auth $auth)
    {
        $this->server = $server;
        $this->providers = $providers;
        $this->app = App::getFacadeRoot();
        $this->auth = $auth;
    }

    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     * @param string[]                 ...$guards
     *
     * @return mixed
     */
    public function handle(Request $request, Closure $next, ...$guards)
    {
        // Get the auth guard if has to check the default guard
        $guards = GuardChecker::getAuthGuards($request);

        // If don't has any guard follow the flow
        if (0 === count($guards)) {
            return $next($request);
        }

        $psr = (new DiactorosFactory())->createRequest($request);

        try {
            $psr = $this->server->validateAuthenticatedRequest($psr);

            $tokenId = $psr->getAttribute('oauth_access_token_id');

            if (!$tokenId) {
                throw new AuthenticationException('Unauthenticated', $guards);
            }

            $accessToken = $this->providers->findForToken($tokenId);

            if (!$accessToken) {
                throw new AuthenticationException('Unauthenticated', $guards);
            }

            if (in_array($accessToken->provider, $guards, true)) {
                $this->authenticate([$accessToken->provider]);
            } else {
                throw new AuthenticationException('Unauthenticated.', $guards);
            }

            return $next($request);
        } catch (OAuthServerException $e) {
            throw new AuthenticationException('Unauthenticated.', $guards);
        }

        return $next($request);
    }

    /**
     * Determine if the user is logged in to any of the given guards.
     *
     * @param array $guards
     *
     * @throws \Illuminate\Auth\AuthenticationException
     */
    protected function authenticate(array $guards)
    {
        if (empty($guards)) {
            return $this->auth->authenticate();
        }

        foreach ($guards as $guard) {
            if ($this->auth->guard($guard)->check()) {
                return $this->auth->shouldUse($guard);
            }
        }

        throw new AuthenticationException('Unauthenticated.', $guards);
    }
}

```

And I override the Authenticate middleware in **Kernel.php**
```
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\MultiProviderAuthenticate::class,
        //'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
```

Then in my controller, I case use _Auth::user()_ or _request()->user()_ and I always have the user type associated to my token.

What do you think of it ?

**Comment by sfelix-martins** [comment]
@odupont it’s looks good! Your solution will leave easier the use of the package. Make a pull request, please.

**Comment by odupont** [comment]
@sfelix-martins thank you, working on it

**Comment by sfelix-martins** [comment]
@mkconsultpm The @odupont solution is actually on branch `master`. You can see the [docs](https://github.com/sfelix-martins/passport-multiauth) to more info how to use.
