### ISSUE TITLE
Details of another user can be access by changing the provider when requesting a refreshing token

### ISSUE THREAD

**Issue by pktharindu** [sfelix-martins/passport-multiauth#25]
I have two auth providers: `users` and `admins`.
Let's say I used `users` provider to retrieve `access_token` and `refresh_token` using password grant. Then I can use that `refresh_token` to refresh the tokens as described [here](https://github.com/sfelix-martins/passport-multiauth#refreshing-tokens).

So even though I'm using a `refresh_token` which was issued for a `user`, if I change the provider param to `admins` when refreshing the tokens, the new tokens I receive will be linked to an `admin` instead. So as long as I have an 'admin' with the same id as a 'user' I can access the system as an admin through the user and vice-versa.

How can I prevent this?

**Comment by sfelix-martins** [comment]
@pktharindu , thanks for your issue.

For now the responsibility to don't refresh a token with incorrect provider are your. But the package should block this behavior. The `access_token` created to one provider only must to be refreshed by same provider. I will check this issue to prevent this behavior.

**Comment by emircansancar** [comment]
Did you find a solution to this? because without refresh_token, users cannot refresh token.

**Comment by kazemmdev** [comment]
I have same problem!!!!
Is there any solution @sfelix-martins ?
