### ISSUE TITLE
MultiAuthenticate Middleware missing

### ISSUE THREAD

**Issue by gailpasiona** [sfelix-martins/passport-multiauth#26]
Hi,

Im getting this error in my laravel app.

"ReflectionException
Class SMartins\PassportMultiauth\Http\Middleware\MultiAuthenticate does not exist"

When I checked in the vendor\smartins\passport-multiauth directory MultiAuthenticate.php is missing in the Middleware folder.

Im able to get this working by manually replacing the files with those files in package's github. I just want to ask if there is a way to solve this aside from manually copying files.

Thank you very much.

**Comment by sfelix-martins** [comment]
Hi, what version you are using? Probably you installed the stable version 1.0 and follow the instructions of dev-master branch. This class really not found on version 1.0. I recommend you require the dev-master branch to solve your problem.
