### ISSUE TITLE
it got this "Method Illuminate\\Database\\Query\\Builder::getAuthIdentifierName does not exist"

### ISSUE THREAD

**Issue by Thoimanich** [sfelix-martins/passport-multiauth#27]

**Comment by sfelix-martins** [comment]
Please, give more details of the error.

**Comment by ycit-alzuabiri** [comment]
BadMethodCallException: Call to undefined method App\Vistor::getAuthIdentifierName() in file C:\laragon\www\Events\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php on line 50
