### ISSUE TITLE
I faced a strange issue

### ISSUE THREAD

**Issue by tecionsdev** [sfelix-martins/passport-multiauth#31]
if the name of the model is like 'model_a' then it does not work there should not be any _ in model

**Comment by sfelix-martins** [comment]
omg, very strange. I will check it. Thanks

**Comment by tecionsdev** [comment]
for example, I created a model CreateEmployee with -m so database table is  create_employes while post request "provider": "create_employes" . its not working

later I created another model name Employee and database   is employees its working now

**Comment by sfelix-martins** [comment]
@tecionsdev Six months later... Did you solve this problem or just changed the name of your table?
