### ISSUE TITLE
Doesn't seem to work with client_credentials grant. 

### ISSUE THREAD

**Issue by gkarugi** [sfelix-martins/passport-multiauth#33]
As the client credentials grant is used for machine to machine authentication, it does not have a provider by default. So I get an error while trying to obtain a token using client credentials  grant.

This is the database exception I am getting

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'provider' cannot be null (SQL: insert into `oauth_access_token_providers` (`oauth_access_token_id`, `provider`, `created_at`, `updated_at`) values (6fc58009ff4ad74ea68041147e3e9985a5a68e735beb5fcea4f831dc5f7d895eb6eca502fc9c6810, , 2018-07-10 11:33:08, 2018-07-10 11:33:08))
```

**Comment by sfelix-martins** [comment]
@gkarugi Thank you for sending. I will check. A pull request would be welcome ;)

**Comment by sfelix-martins** [comment]
@gkarugi Could you provide more details on how to simulate the error?

**Comment by bunnadev** [comment]
Hello, it's seem same issue with me, when I try to get access token with this data

 'grant_type' => 'client_credentials',
 'client_id' => 'client-id',
 'client_secret' => 'client-secret',
'scope' => 'your-scope',

then I can't use access_token in result: {"message":"Unauthenticated."}

**Comment by sfelix-martins** [comment]
@huypn 
Sorry, but can't simulate this error. My steps was:

1. Generate encryption keys:

```sh
php artisan passport:install
```

2. Follow the Client Credentials config steps from [Laravel Passport docs](https://laravel.com/docs/5.6/passport#client-credentials-grant-tokens)

3. Issue token using generated encryption key on first step:

```http
POST /oauth/token HTTP/1.1
Host: homestead.test
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: 5bb1f47c-0d2e-3df9-d508-7a773bd90d47

grant_type=client_credentials&client_id=1&client_secret=C85bTusmY2Eydr7jrVIqd8b8vIl2huoDWMYehN16&scope=
```
and received response:

```json
{
    "token_type": "Bearer",
    "expires_in": 31536000,
    "access_token": "eyJ0eXAiOiJKV1Q..."
}
```

4. I send a request to my route wrapped with `'client' => Laravel\Passport\Http\Middleware\CheckClientCredentials::class` middleware passing the `Authorization` header with access token:

```php
// The route
Route::get('/client_user', function (Request $request) {
    return json_encode(['message' => 'authenticated']);
})->middleware('client');
`````

And the request:

```http
GET /api/client_user HTTP/1.1
Host: homestead.test
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1Q...
Cache-Control: no-cache
Postman-Token: 48816d4f-edc9-6fce-17db-d26b92e67c83
```

and the response was:

```json
{"message":"authenticated"}
```

In the package core, the event `Laravel\Passport\Events\AccessTokenCreated` is listened. When an access token is created the following code are executed:

```php
Event::listen(AccessTokenCreated::class, function ($event) use ($providers) {
    $provider = config('auth.guards.api.provider');

    $providers->create($event->tokenId, $provider);
});
```

I think that this config can to be not defined. Please check it. 

Feel free to ask!

**Comment by sfelix-martins** [comment]
If the solution above don't solved the problem please reopen the issue.
