### ISSUE TITLE
Auth::guard('admin')->attempt($credentials) is not working

### ISSUE THREAD

**Issue by nicolasflorth** [sfelix-martins/passport-multiauth#36]
Hi Samuel,
My problem is that  `Auth::guard('admin')->attempt($credentials)` is not working. Error: `Method attempt does not exist.`

I couldn't find any solution anywhere. 
Somebody from this post [https://github.com/laravel/framework/issues/21194](url) says to use `\Auth::setUser($token->user);` as an workaround, but he also say that I will have 

> to override register and all auth functions as well

....is getting complicated, I don't understand how to do that.

Can you please advice how this should be done maybe in a more simple way?

Thank you!
Nicolae

**Comment by sfelix-martins** [comment]
Hi Nicolas, 
I think that the login with `Auth::attempt($credentials)` is just authentication with session.
In the first comment of the [issue](https://github.com/laravel/framework/issues/21194) has the answer:

`Yes attempt() doesn't work with token guards, only Guards that implement StatefulGuard`

To stateless auth using laravel passport you should send a request to `oauth/token` route passing you user credentials to get the access token. Ex.:

```http
POST /oauth/token HTTP/1.1
Host: localhost
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache

{
    "username":"user@domain.com",
    "password":"password",
    "grant_type" : "password",
    "client_id": "client-id",
    "client_secret" : "client-secret",
}
```

And this package add capabilities for you pass the param `provider` for request above and retrieve token to an specific model (User, Admin, Customer, etc.).

Maybe you may want to create a token manually. In the answer for issue #32 has an example how to do this.

Regards,
Samuel Martins
