### ISSUE TITLE
Create token manually

### ISSUE THREAD

**Issue by ayman1-elmalah** [sfelix-martins/passport-multiauth#38]
When i'm using laravel passport, i can create new token manually and send i to user, this function createToken works well but not with multiauth, what is the function that i can use to do that ??
![7686543213456789](https://user-images.githubusercontent.com/37438338/43348556-f2b5815a-91fa-11e8-88b6-766322ff99b4.PNG)

**Comment by sfelix-martins** [comment]
Hi @ayman1-elmalah, 
On issue #32 I answered it. You just need wrap your route with the middleware `'oauth.providers' => \SMartins\PassportMultiauth\Http\Middleware\AddCustomProvider::class,`. And pass the param `provider` with the guard of the model to who you want create the token.
