### ISSUE TITLE
i got an error Call to undefined method Illuminate\Database\Query\Builder::getAuthPassword()

### ISSUE THREAD

**Issue by kobidkunda** [sfelix-martins/passport-multiauth#4]
while posting through post man with this data i got error

"Call to undefined method Illuminate\Database\Query\Builder::getAuthPassword()"

`{
	"grant_type" : "password",
	"client_id" : "3",
	"client_secret": "g6zrsKw7SCel0TraN6T60FV3iwWoRhu0nKu8hYp0",
	"username": "l@l.com",
	"password": "l@l.com",
	"provider" : "customers"
}`

**Comment by kobidkunda** [comment]
Please update the Model Accordingly

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens; 

class Customer extends Authenticatable
{
    use Notifiable, HasApiTokens;

  // protected $guard = ['bus', 'bus-api'];


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
         'email', 'password',
    ];




    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



}`

**Comment by sfelix-martins** [comment]
Good @kobidkunda. I will update the instructions so this setting gets clearer. Thanks.
