### ISSUE TITLE
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR) Call to a member function setCookie() on null

### ISSUE THREAD

**Issue by jumenitech** [sfelix-martins/passport-multiauth#40]
I get this error when i try to access the site after i implemented the package on my site

```
// If don't has any guard follow the flow
        if (empty($guards)) {
          return $this->authenticate($guards);
       }
```

i fixed it by returning changing the method in MultiAuthenticate middleware class like so

```
// If don't has any guard follow the flow
        if (empty($guards)) {
           $this->authenticate($guards);
           return $next($request);
         }
```

maybe im doing something wrong.... but after that change, everything works perfectly

**Comment by pedmindset** [comment]
Had the same issue, this fixed it

**Comment by sfelix-martins** [comment]
Thanks brow. Please create a pull request.

**Comment by pedmindset** [comment]
Ok will do that, will use my personal account rather than the company account @jumeni

**Comment by sfelix-martins** [comment]
Ok @pedmindset . I am waiting. Thanks
