### ISSUE TITLE
Unauthenticated when using auth:admin

### ISSUE THREAD

**Issue by nicolasflorth** [sfelix-martins/passport-multiauth#44]
When doing a request to any protected route, using, after succesull login 
`Route::group(['middleware' => 'auth:admins'], function(){
Route::get('customers', 'CustomerController@index');
});` 
will always return Unauthenticated.

This MultiAuth package was succesfull installed, and I am able to login to any user category I want, like Users or Admins.
From what I know in this expression "auth:admins", admins is the provider defined in auth.php.
If so, I don't understand why is still Unauthenticated when access_token from oauth/token is generated and sent in Header.

My experience with Authentication and access_token started with this project, so I don't have to many knowledge and I suppose my problem is because I don't know how to keep the access_token on the server side and check it again when is a new Request.
Frontend and Backend in my case are 2 separate projects.

For the moment, I am doing the Login (where is the oauth/token call). I return the response from oauth/token that have access_token and refresh_token with expiration date and set The Authentication Header with Beared on Frontend. 
In this moment, Frontend has the access_token as header.
If I am doing a new request to Backend, the Request will have the access_token but the Response Headers will not heave it and I think this is the problem. Or not?

I hope my problem description is not too long and hard to understand as I really need to know haw to keep the access_token on Response and compare it on each new request with the access_token sent to Frontend.
Thank you!

**Comment by sfelix-martins** [comment]
Hi. Please send your `config/auth.php`, `app/Http/Kernel.php` and `AuthServiceProvider`. I need too an example of the request that you are sending to API with the params and headers. Please, send too your `routes`.

**Comment by nicolasflorth** [comment]
Hi Samuel! 
[files.zip](https://github.com/sfelix-martins/passport-multiauth/files/2265681/files.zip)

I attached all this files, plus the LoginController and a video to see the request headers
Thanks a lot!
Nick

**Comment by nicolasflorth** [comment]
Anything on this?

**Comment by nicolasflorth** [comment]
I think I understand where is the problem.
on PassportCustomProviderAccessToken.php is this line 
`\Config::set('auth.guards.api.provider', $access_token->provider);`
This basically is saying that I will have to use 
`Route::group(['middleware' => 'auth:api'], function(){` 
because api.provider was set above as any route will come from  $access_token->provider

**Comment by MarkVilludo** [comment]
I also encountered this problem. After successful login and use the response access_token to access the middleware auth:admin it shows always "Unauthenticated". Please help on this issue

**Comment by sfelix-martins** [comment]
Sorry for lazy to answer. Please send me your configs, routes and another files related files to simulate the problem.

**Comment by MarkVilludo** [comment]
Hi Sir Samuel!

Thanks for the feedback. Noted sir, Here's attached files with the screenshots of test API's.
Please help :/
[config&etc.zip](https://github.com/sfelix-martins/passport-multiauth/files/2374676/config.etc.zip)

**Comment by sfelix-martins** [comment]
I created a [demo project](https://github.com/sfelix-martins/passport-multiauth-demo) with implementation. You can check it and compare. Thanks.
