### ISSUE TITLE
ErrorException: Array to string conversion in GuardChecker.php

### ISSUE THREAD

**Issue by Versoo** [sfelix-martins/passport-multiauth#48]
> {
    "status": "error",
    "code": 0,
    "message": "Array to string conversion",
    "exception": "ErrorException: Array to string conversion in /vagrant/www/vendor/smartins/passport-multiauth/src/Guards/GuardChecker.php:54\nStack trace:\n#0 /vagrant/www/vendor/smartins/passport-multiauth/src/Guards/GuardChecker.php(54): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Array to string...', '/vagrant/www/ve...', 54, Array)\n#1 /vagrant/www/vendor/smartins/passport-multiauth/src/Guards/GuardChecker.php(42): SMartins\\PassportMultiauth\\Guards\\GuardChecker::defaultGuardProvider(Array)\n#2 /vagrant/www/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1009): SMartins\\PassportMultiauth\\Guards\\GuardChecker::SMartins\\PassportMultiauth\\Guards\\{closure}(Array, 0)\n#3 /vagrant/www/vendor/smartins/passport-multiauth/src/Guards/GuardChecker.php(43): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))\n#4 /vagrant/www/vendor/smartins/passport-multiauth/src/Http/Middleware/MultiAuthenticate.php(124): SMartins\\PassportMultiauth\\Guards\\GuardChecker::getGuardsProviders(Array)\n#5 /vagrant/www/vendor/smartins/passport-multiauth/src/Http/Middleware/MultiAuthenticate.php(82): SMartins\\PassportMultiauth\\Http\\Middleware\\MultiAuthenticate->authenticateTokenGuard(Object(SMartins\\PassportMultiauth\\Provider), Array)\n#6 /vagrant/www/infrastructure/Auth/Middleware/MultiTokenAccessChecker.php(43): SMartins\\PassportMultiauth\\Http\\Middleware\\MultiAuthenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), Array)\n#7 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Infrastructure\\Auth\\Middleware\\MultiTokenAccessChecker->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'admin')\n#8 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#9 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#10 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#11 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#12 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))\n#13 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#14 /vagrant/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#15 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))\n#16 /vagrant/www/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#17 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#18 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#19 /vagrant/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#20 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#21 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#22 /vagrant/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#23 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#24 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#25 /vagrant/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#26 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#27 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#28 /vagrant/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#29 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#30 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#31 /vagrant/www/vendor/hyn/multi-tenant/src/Middleware/EagerIdentification.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#32 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Hyn\\Tenancy\\Middleware\\EagerIdentification->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#33 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#34 /vagrant/www/vendor/hyn/multi-tenant/src/Middleware/HostnameActions.php(76): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#35 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Hyn\\Tenancy\\Middleware\\HostnameActions->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#36 /vagrant/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#37 /vagrant/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#38 /vagrant/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#39 /vagrant/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))\n#40 /vagrant/www/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#41 {main}",
    "line": 54,
    "file": "/vagrant/www/vendor/smartins/passport-multiauth/src/Guards/GuardChecker.php"
}

**Token payload**

> {
  "aud": "2",
   [...]
  "sub": "1",
  "scopes": [],
  "provider": "admins"
}

**My solution: Change $guards to $guards[0]**
`
public static function getGuardsProviders($guards)
{
    return collect($guards[0])->mapWithKeys(function ($guard) {
        return [GuardChecker::defaultGuardProvider($guard) => $guard];
    });
}`

I send provider name with tokens and I have problem like on top. I found solution but I'm not sure it is good. I know, I shouldn't change files at package but I was searching a problem and discovered something like that. Someone have that same problem, and have better idea?

**Comment by sfelix-martins** [comment]
@Versoo Thanks for your issue. OMG! :astonished: I will check it! 

About "I know, I shouldn't change files at package" feel free to solve errors and contribute to improve the package! :+1: 

Please you can give more details how to you passed your guards on `auth` middleware?

**Comment by Versoo** [comment]
@sfelix-martins 

I'm using my repository of [Larapi]([https://github.com/Versoo/larapi) and in Infrastructure\Http\RouteServiceProvider.php I added:

`'middleware' => ['auth:api,admin']`

**Command "route:list" return:**

[Screenshot](http://prntscr.com/klzd0z)

If you need something else, please write. I will send ;)

**Comment by sfelix-martins** [comment]
I can’t simulate the error on default laravel structure. Can you send me your project files? Or instructions on  how you set up with your Larapi project.

**Comment by sfelix-martins** [comment]
If the problem has not been resolved reopen the issue.
