### ISSUE TITLE
Not Able to authenticate 

### ISSUE THREAD

**Issue by jacinto-joao** [sfelix-martins/passport-multiauth#49]
Hi @sfelix-martins , 

How do you authenticate a user from another table?

Like on my side I have `User and MerchantAuth` Model.

To authenticates users, everything goes well, without any problem.

But I'm struggling to authenticate MerchantsAuth users, I tried to follow all the steps you have provided, but I can't see it working.

This what I got so far:
Guards

![image](https://user-images.githubusercontent.com/19816874/44622857-b1cda900-a8c1-11e8-986a-6cb915fa4668.png)

Providers
![image](https://user-images.githubusercontent.com/19816874/44622863-c742d300-a8c1-11e8-91b9-f44f18b5011d.png)

Kernel Middleware Adjustment
![image](https://user-images.githubusercontent.com/19816874/44622884-1852c700-a8c2-11e8-87f0-bb8b520d95e6.png)

AuthController
`public function login(Request $request)
   {
   		$request->validate([
   			'email'		=>'required|email',
   			'password'	=>'required',
   			'remember_me'=>'boolean'
   		]);

   		$credentials = $request->only('email','password');

   		if(!auth()->attempt($credentials)){
   			return response()->json([
   				'errors'	=>[
   					'root'	=>'Your email or password doesen\'t match with our records.'
   				]
   			],401);
   		}

   		$user = $request->user();

   		$tokenResult = $user->createToken('Personal Access Token');
   		$token 		 = $tokenResult->token;

   		if($request->remember_me){
   			$token->expires_at = Carbon::now()->addWeeks(1);
   		}

   		$token->save();

   		return response()->json([
   			'data'	=>[
   				'access_token'	=> $tokenResult->accessToken,
   				'token_type'	=> 'Bearer',
   				'expires_at'	=>Carbon::parse(
   					$tokenResult->token->expires_at
   				)->toDateTimeString()
   			]
   		]);
   }`

Postman Test

![image](https://user-images.githubusercontent.com/19816874/44622895-6b2c7e80-a8c2-11e8-83eb-5487aab25825.png)

Results,
![image](https://user-images.githubusercontent.com/19816874/44622898-7bdcf480-a8c2-11e8-8673-3d4e2af5f15d.png)

From what I can see it's still looking for users table and not be checking the merchant table,

So any help it would be appreciated, and just to mention that in this stage, I just want it to authenticate
Username and Password and not the entire OAuth process.

**Comment by sfelix-martins** [comment]
@jjoao07 Firstly, thanks for you detailed issue. It's very helpful.

Your configs are correct. The error is to use the method `attemp()` from auth manager. The attempt method uses the default guard `web` and the guard `web` uses the driver `session` with provider `users`:

```php
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        // ...
    ],
```

To change the guard you should call the method `shouldUse()` passing the guard. In your case should look like `Auth::shouldUse('merchant')` and after call the `attempt($credentials)` method. **But** this would work if the driver were `session`. The `passport` driver don't has the `attempt` method.

In short, you **can't** use the `auth()->attemp($credentials)` with laravel passport.

The laravel passport in your core validate the user credentials using the following method from `Laravel\Passport\Bridge\UserRepository`. This method is called on route `oauth/token`:

```php
    public function getUserEntityByUserCredentials($username, $password, $grantType, ClientEntityInterface $clientEntity)
    {
        $provider = config('auth.guards.api.provider');

        if (is_null($model = config('auth.providers.'.$provider.'.model'))) {
            throw new RuntimeException('Unable to determine authentication model from configuration.');
        }

        if (method_exists($model, 'findForPassport')) {
            $user = (new $model)->findForPassport($username);
        } else {
            $user = (new $model)->where('email', $username)->first();
        }

        if (! $user) {
            return;
        } elseif (method_exists($user, 'validateForPassportPasswordGrant')) {
            if (! $user->validateForPassportPasswordGrant($password)) {
                return;
            }
        } elseif (! $this->hasher->check($password, $user->getAuthPassword())) {
            return;
        }

        return new User($user->getAuthIdentifier());
    }
```
You can create a method like the method above to validate your user credentials. 

The next step is relate the token that will be created when you call `createToken('My token')` method with the correct provider. In your case `merchant_auth`.

In the actual plugin version (`2.0.2`), the way to create this relationship is wrap your login route with the middleware `oauth.providers` and pass the param `provider` in your request passing the desired provider as explained on #32 .

But has an opened pull request #45  with new method `createToken` to not be necessary pass the `provider` param on request. On create token from branch `new-feature-manage-tokens` you just need call the method `createToken` from `SMartins\PassportMultiauth\HasMultiAuthApiTokens` trait. The method will get the correct provider from model and create the token correctly.

To test with the new feature you just need change the version into your project `composer.json` file to:

```json
"smartins/passport-multiauth": "dev-new-feature-manage-tokens"
```

and run `composer update smartins/passport-multiauth`

I hope it helps!

**Comment by jacinto-joao** [comment]
Hi @sfelix-martins, thanks for your feedback.

Let me go through it and will let u know where I end up.

Thanks

**Comment by jacinto-joao** [comment]
Hi @sfelix-martins, I got the auth working now for both Users and Merchant

this how my controller looks like 

`
   public function authenticate(Request $request)
   {
     $provider = config('auth.guards.api.provider');

     if (is_null($model = config('auth.providers.'.$provider.'.model'))) {
         throw new RuntimeException('Unable to determine authentication model from configuration.');
     }

     if (method_exists($model, 'findForPassport')) {
         $user = (new $model)->findForPassport($request->get('email'));
     } else {
         $user = (new $model)->where('email', $request->get('email'))->first();
     }

     if (! $user) {
         return response()->json([
            'errors' =>[
               'root'   =>'Your email or password doesen\'t match with our records.'
            ]
         ],401);
     } elseif (method_exists($user, 'validateForPassportPasswordGrant')) {
         if (! $user->validateForPassportPasswordGrant($request->get('password'))) {
             return response()->json('user2',201);
         }
     } elseif (! $this->hasher->check($request->get('password'), $user->getAuthPassword())) {
         return response()->json('user3',201);
     }

     $tokenResult = $user->createToken('Personal Access Token');
     $token       = $tokenResult->token;

      if($request->remember_me){
         $token->expires_at = Carbon::now()->addWeeks(1);
      }

      $token->save();

     return response()->json([
         'data'   =>[
            'access_token'=>$tokenResult->accessToken,
            'token_type'   => 'Bearer',
            'expires_at'   =>Carbon::parse(
               $tokenResult->token->expires_at
            )->toDateTimeString()
         ]
     ],201);
   }

`

The only issue I'm facing now is to get an authenticated user, I cannot get any of both instances,
either user or merchant.

I tried passing the middleware `"auth:api" and auth:merchant` but none of them is working and my kernel.php API middleware I tried to adjust by duplicating the api to the merchant and it looks like this.

![image](https://user-images.githubusercontent.com/19816874/44627984-217e7b00-a938-11e8-9f1a-b1e52480f3d0.png)

And my route looks like this

![image](https://user-images.githubusercontent.com/19816874/44627996-44109400-a938-11e8-8f04-f7daccda2d50.png)

Controller
![image](https://user-images.githubusercontent.com/19816874/44628003-7a4e1380-a938-11e8-9653-8a272e72925d.png)

Postman
![image](https://user-images.githubusercontent.com/19816874/44628006-8cc84d00-a938-11e8-9f4c-cfe1ce48f06e.png)

Second attempt with auth:merchant
![image](https://user-images.githubusercontent.com/19816874/44628017-c600bd00-a938-11e8-8c1a-d72fe3db26bc.png)

Getting the same results

![image](https://user-images.githubusercontent.com/19816874/44628024-dadd5080-a938-11e8-9483-ae8148a5ade8.png)

Is there something else am I missing to get the right authenticated user for both instances or providers?

**Comment by sfelix-martins** [comment]
The params passed to `auth` middleware refers the guards on `config/auth.php`.

How you generate the personal access token? Wrapping your route with `oauth.providers` middleware and passing the param `provider` on request, or get updates from branch `new-feature-manage-tokens`?

**Comment by jacinto-joao** [comment]
This how do I generate tokens

![image](https://user-images.githubusercontent.com/19816874/44629077-54ca0580-a94a-11e8-9e2a-8c17ba8d29ef.png)

 from the login controller, after successful authentication.

Let me update the branch and see how it goes.

**Comment by sfelix-martins** [comment]
Ok, but in your request to login route? Wrapped you the route with `oauth.providers` middleware and sent the `provider` param on request?

**Comment by jacinto-joao** [comment]
Yes I did that,

`Route::group(['prefix'=>'auth','namespace'=>'Auth\Passport','middleware'=>'oauth.providers'], function(){

		Route::post('signup','AuthController@signup');
		Route::post('login','AuthController@authenticate');
		
	});`

**Comment by sfelix-martins** [comment]
Do you encountered any solution to your problem?

**Comment by jacinto-joao** [comment]
Hi @sfelix-martins ,

Yes, I did find a solution.

Passport worked well, but I have found a better solution the one I have been looking for on first place with Tymon/JWT.

check the link below

https://github.com/tymondesigns/jwt-auth/issues/1626#issuecomment-416237597

**Comment by sfelix-martins** [comment]
@jjoao07

It’s a good alternative!
