### ISSUE TITLE
Access token works for both Models

### ISSUE THREAD

**Issue by Abonive** [sfelix-martins/passport-multiauth#5]
The package works fine as it is, but the issued token does work for both providers if they have a user with the same id.

I change the middleware from `auth:admin_api` to `auth:api` and on both, it returned user for their respected provider.

And that is a serious security issue.

Any idea how to prevent that?

**Comment by sfelix-martins** [comment]
I encountered the same error and sent any changes to branch ‘master’. I don’t make a release because I want to test more a bit. But you can help me with this! I you wish, use the latest commit of branch master and check if your problem has been solved. On latest README has any instructions too use this version. Thanks for issue. I hope it helps.

**Comment by Abonive** [comment]
I just did a quick check and it works, fine.
 I've requested token for an admin and I've tried to get a user from the route with `auth:api` middleware and it redirected me to login page.

I will do some more testing but seems to work fine.

**Comment by sfelix-martins** [comment]
Pass on your request the header ‘accept: application/json’. Probably you will receive a 401(unauthenticated)

**Comment by Abonive** [comment]
Ok, just tried that. Works fine. Good work man!

**Comment by sfelix-martins** [comment]
Very good! When I create the new release this issue will be closed.

**Comment by Abonive** [comment]
One more thing, as they all the models use the HasApiToken trait and this trait is not made to be used like we use passport package. 
So refactoring this trait to work correctly with this package would make this complete.

**Comment by sfelix-martins** [comment]
I think that we can check this possibility together. Please, create a issue with your improvement request.

**Comment by sfelix-martins** [comment]
The release [v1.0.0](https://github.com/sfelix-martins/passport-multiauth/releases/tag/v1.0.0) fix the problem with access tokens working with many models with same database id
