### ISSUE TITLE
Auth middleware: Too few arguments to function

### ISSUE THREAD

**Issue by saeldion** [sfelix-martins/passport-multiauth#52]
After setting up the package according to the instructions I get the following error:
`Symfony\Component\Debug\Exception\FatalThrowableError: Too few arguments to function Illuminate\Auth\Middleware\Authenticate::authenticate(), 1 passed in /app/vendor/smartins/passport-multiauth/src/Http/Middleware/MultiAuthenticate.php on line 141 and exactly 2 expected in file /app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php on line 55`
when using the middleware `auth:api` (or with any guard).

It looks like in some recent version of Laravel, the authenticate method signature was changed to include the request ([commit](https://github.com/laravel/framework/commit/7c6ae9ad189febef82e41279937004caa1bd7411#diff-1ceb87384700ae501cf3159996b23dc9)), in Illuminate\Auth\Middleware\Authenticate. This makes the attached middleware in this package incompatible with this version of Laravel.

Should be fixable by calling authenticate like this: `$this->authenticate($request, $guards);` on line 66 in `SMartins\PassportMultiauth\Http\Middleware\MultiAuthenticate`. Don't know if anything else has been changed that might affect this.

Running:
* Laravel 5.7.1
* Passport: 7.0.1
* passport-multiauth: 3.0.0

**Comment by saeldion** [comment]
Noticed that `authenticate` is also called on line 141. Request would be needed here as well

**Comment by sfelix-martins** [comment]
I need check the compatibility with laravel 5.7. A pull request would be good... :)

**Comment by sfelix-martins** [comment]
The problem is the method `authenticate` from laravel 5.7. Now the method receives 2 params, request and the guards. On older versions just the param guards was required.

**Comment by sfelix-martins** [comment]
I'm planing add compatibility with laravel 5.7 ASAP. A pull request would be welcome.

**Comment by sfelix-martins** [comment]
@Ardan The branch `4.0` add compatibility with laravel 5.7. I'll test more a bit, but I'll publish a new release ASAP. To use from branch now you just need change your package version on composer to `"smartins/passport-multiauth": "4.0.x-dev"`. Don't forget the add the attributes `"minimum-stability": "dev"` and `"prefer-stable": true`.
