### ISSUE TITLE
cant install on laravel 5.5

### ISSUE THREAD

**Issue by nerminba** [sfelix-martins/passport-multiauth#53]
I just setup new laravel 5.5 project and tried to install this package and I get the following. I will paste it all in here.

What can I do to make it install.

composer require smartins/passport-multiauth
Using version ^3.0 for smartins/passport-multiauth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.43
    - Conclusion: don't install laravel/framework v5.5.43
    - laravel/passport v5.0.0 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v5.0.1 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v5.0.2 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v5.0.3 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v6.0.0 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v6.0.1 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v6.0.2 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v6.0.3 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v6.0.4 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v6.0.5 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v6.0.6 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v6.0.7 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v7.0.0 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - laravel/passport v7.0.1 requires illuminate/http ~5.6 -> satisfiable by illuminate/http[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.2].
    - don't install illuminate/http v5.6.0|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.1|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.10|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.11|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.12|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.13|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.14|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.15|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.16|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.17|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.19|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.2|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.20|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.21|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.22|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.23|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.24|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.25|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.26|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.27|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.28|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.29|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.3|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.30|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.31|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.32|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.33|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.34|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.35|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.36|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.37|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.38|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.4|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.5|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.6|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.7|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.8|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.6.9|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.7.0|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.7.1|don't install laravel/framework v5.5.43
    - don't install illuminate/http v5.7.2|don't install laravel/framework v5.5.43
    - Installation request for laravel/framework (locked at v5.5.43, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.43].
    - Installation request for smartins/passport-multiauth ^3.0 -> satisfiable by smartins/passport-multiauth[v3.0.0].
    - Conclusion: don't install paragonie/random_compat v9.99.99|install laravel/passport v5.0.0|install laravel/passport v5.0.1|install laravel/passport v5.0.2|install laravel/passport v5.0.3|install laravel/passport v6.0.0|install laravel/passport v6.0.1|install laravel/passport v6.0.2|install laravel/passport v6.0.3|install laravel/passport v6.0.4|install laravel/passport v6.0.5|install laravel/passport v6.0.6|install laravel/passport v6.0.7|install laravel/passport v7.0.0|install laravel/passport v7.0.1
    - Conclusion: remove paragonie/random_compat v9.99.99|install laravel/passport v5.0.0|install laravel/passport v5.0.1|install laravel/passport v5.0.2|install laravel/passport v5.0.3|install laravel/passport v6.0.0|install laravel/passport v6.0.1|install laravel/passport v6.0.2|install laravel/passport v6.0.3|install laravel/passport v6.0.4|install laravel/passport v6.0.5|install laravel/passport v6.0.6|install laravel/passport v6.0.7|install laravel/passport v7.0.0|install laravel/passport v7.0.1
    - smartins/passport-multiauth v3.0.0 requires laravel/passport ^3.0|^4.0|^5.0|^6.0|^7.0 -> satisfiable by laravel/passport[v3.0.0, v3.0.1, v3.0.2, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v5.0.0, v5.0.1, v5.0.2, v5.0.3, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.0.5, v6.0.6, v6.0.7, v7.0.0, v7.0.1].
    - laravel/passport v3.0.0 requires league/oauth2-server ^6.0 -> satisfiable by league/oauth2-server[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1].
    - laravel/passport v3.0.1 requires league/oauth2-server ^6.0 -> satisfiable by league/oauth2-server[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1].
    - laravel/passport v3.0.2 requires league/oauth2-server ^6.0 -> satisfiable by league/oauth2-server[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1].
    - laravel/passport v4.0.0 requires league/oauth2-server ^6.0 -> satisfiable by league/oauth2-server[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1].
    - laravel/passport v4.0.1 requires league/oauth2-server ^6.0 -> satisfiable by league/oauth2-server[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1].
    - laravel/passport v4.0.2 requires league/oauth2-server ^6.0 -> satisfiable by league/oauth2-server[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1].
    - laravel/passport v4.0.3 requires league/oauth2-server ^6.0 -> satisfiable by league/oauth2-server[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1].
    - league/oauth2-server 6.0.0 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - league/oauth2-server 6.0.1 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - league/oauth2-server 6.0.2 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - league/oauth2-server 6.1.0 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - league/oauth2-server 6.1.1 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - Can only install one of: paragonie/random_compat[v2.0.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.10, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.11, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.12, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.13, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.14, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.15, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.16, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.17, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.7, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.8, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.9, v9.99.99].
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].

Installation failed, reverting ./composer.json to its original content.

**Comment by nerminba** [comment]
Well I managed to solve it! :)

**Comment by Hexor** [comment]
does it been solved?

**Comment by sfelix-martins** [comment]
@nikocraft Can you share your solution to helps @Hexor ?

**Comment by Hexor** [comment]
> @nikocraft Can you share your solution to helps @Hexor ?

I use this version which worked in laravel 5.5

 `        "smartins/passport-multiauth": "v3.0.0"`
