### ISSUE TITLE
Too few arguments to function Illuminate\\Routing\\Router::{closure}(), 0 passed in /Users/markvilludo/Documents/Activity/MultiAuth/vendor/laravel/framework/src/Illuminate/Routing/Route.php on line 198 and exactly 1 expected

### ISSUE THREAD

**Issue by MarkVilludo** [sfelix-martins/passport-multiauth#54]
Hi Sir!

After setting up the package according to the instructions I get the following error when accessing the auth:admin middleware.

Too few arguments to function Illuminate\\Routing\\Router::{closure}(), 0 passed in /Users/markvilludo/Documents/Activity/MultiAuth/vendor/laravel/framework/src/Illuminate/Routing/Route.php on line 198 and exactly 1 expected.

Please help to fixed this issues. Thanks!

**Comment by sfelix-martins** [comment]
Hi.

Please, I need more details how to simulate this error. What’s version from laravel framework, laravel passport and multiauth package are you using? 

And don’t forget: issues are very good, but we love pull requests too 😍

**Comment by MarkVilludo** [comment]
Okay sir, The laravel version I used is 5.6 and smartins/passport-multiauth": "^3.0. 

Thanks for your feedback sir!

**Comment by sfelix-martins** [comment]
Good! Can you send me your routes, config files, and another file shown on README instructions? 

Thanks

**Comment by MarkVilludo** [comment]
Files is in this comment sir. Please try to check it out. Thank you sir!

https://github.com/sfelix-martins/passport-multiauth/issues/44#issuecomment-420597007

**Comment by sfelix-martins** [comment]
@MarkVilludo 

Sorry for the delay to reply. I tested and the problem that I encountered are on your routes definitions:

```php
Route::group(['middleware' => ['auth:admin']], function () {
    // To it work correctly I needed add the type to param $request
    Route::get('/v1/admin', function ($request) {
        // Get the logged admin instance
        return $request->user('admin'); // You can use too `$request->user('admin')` passing the guard.
    });
});
```

The final code looks like:
```php
Route::group(['middleware' => ['auth:admin']], function () {
    // To it work correctly I needed add the type to param $request
    Route::get('/v1/admin', function (Request $request) {
        // Get the logged admin instance
        return $request->user();
    });
});
```
It solved for me!
