### ISSUE TITLE
redirect to many time 

### ISSUE THREAD

**Issue by michaelnguyen2021** [sfelix-martins/passport-multiauth#59]
when route has auth:{guard} middleware and {guard} has a session driver (not passport driver), Laravel crashes and the browser say TOO_MANY_DIRECTS. I am also using [hesto\multi-auth](https://github.com/Hesto/multi-auth)

L5.7 and passport-multiauth v4.0.0
```php
 // 'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
'auth' => \SMartins\PassportMultiauth\Http\Middleware\MultiAuthenticate::class,
```
If I use normal 'auth' (\Illuminate\Auth\Middleware\Authenticate::class,), it is ok.

**Comment by sfelix-martins** [comment]
@michaelnguyen547 sorry for the delay. Can you solve the error?

**Comment by michaelnguyen2021** [comment]
I still have this problem and don't know why

**Comment by moscoquera** [comment]
i facing this too.... it fails on: validateAuthorization because the authorization header is not set in the basic auth post.

**Comment by sfelix-martins** [comment]
@moscoquera can you send a pull request with the solution or with a unit test failing?

**Comment by moscoquera** [comment]
I don't think a pull request is needed:
in the docs says:
"Replace the middleware Authenticate on app/Http/Kernel $routeMiddleware attribute."

```
class Kernel extends HttpKernel
{
    // ...

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        // 'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth' => \SMartins\PassportMultiauth\Http\Middleware\MultiAuthenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'oauth.providers' => \SMartins\PassportMultiauth\Http\Middleware\AddCustomProvider::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];

    // ...
}
```

auth is usually the middleware used for the web session, don't change auth, just give another name to the passport-multiauth's middleware and use it only in the api endpoints:

```
class Kernel extends HttpKernel
{
    // ...

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.api.multi' => \SMartins\PassportMultiauth\Http\Middleware\MultiAuthenticate::class, //see the name
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'oauth.providers' => \SMartins\PassportMultiauth\Http\Middleware\AddCustomProvider::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];

    // ...
}
```

in your endpoint routes, replace "auth:api" with 'auth.api.multi'

**Comment by sfelix-martins** [comment]
@moscoquera I understood. It's a good solution! 
Could you send a pull request with the change in the README?

**Comment by michaelnguyen2021** [comment]
> @moscoquera I understood. It's a good solution!
> Could you send a pull request with the change in the README?

I've sent a pull request that include @moscoquera suggestions
