### ISSUE TITLE
how to create revoke for tokens

### ISSUE THREAD

**Issue by mohammadnaghibi** [sfelix-martins/passport-multiauth#64]
@sfelix-martins 
how can i create revoke for token in your package

**Comment by sfelix-martins** [comment]
@mohammadnaghibi 

Your model instance that uses the trait `SMartins\PassportMultiauth\HasMultiAuthApiTokens` has the method `tokens()`. This method defines a `hasMany` relationship between `Laravel\Passport\Token` and your model. You can use this to retrieve a list of all of the tokens for a given user:

```php
$userTokens = $userInstance->tokens;
```

The token model itself has a revoke method:

```php
foreach($userTokens as $token) {
    $token->revoke();   
}
```

I hope it helps! I'm waiting your feedback to close this issue.

Thanks.

**Comment by mohammadnaghibi** [comment]
thanks @sfelix-martins  
I want before login ، all tokens created before for this user change to revoked
please help me

**Comment by sfelix-martins** [comment]
Well, probably you will need found the user first to revoke the tokens. If I understood correctly, the solution on my previous comment solve your problem. You just need get your user instance, get the user tokens calling the attribute `tokens`, iterate them and call the `revoke()` method for each.

**Comment by mohammadnaghibi** [comment]
thanks @sfelix-martins
