### ISSUE TITLE
The package confuses with two different guard and same id on two model (table)

### ISSUE THREAD

**Issue by ghost** [sfelix-martins/passport-multiauth#70]
If i try Auth::guard('user-api')->user(); I get a user with id 9, and if I try Auth::guard('admin-api')->user(); I get an admin with id 9. so wierd !!! I checked all the things and they were set correctly but with same token I get two different model instance!

**Comment by ghost** [comment]
please help! my project is in production and now I've faced this bug.

**Comment by sfelix-martins** [comment]
What’s package version are you using?

**Comment by ghost** [comment]
I'm using version 3.0 of this package, laravel 5.6, and passport 7.0

**Comment by sfelix-martins** [comment]
Please, can you test the updates from branch `fix-same-id-model-one-token`?

Change your `composer.json` file:

```json
"minimum-stability": "dev",
"prefer-stable": true,
"require": {
    "smartins/passport-multiauth": "dev-fix-same-id-model-one-token",
}
```

And run `composer update smartins/passport-multiauth`

**Comment by ghost** [comment]
> 
> 
> Please, can you test the updates from branch `fix-same-id-model-one-token`?
> 
> Change your `composer.json` file:
> 
> ```json
> "minimum-stability": "dev",
> "prefer-stable": true,
> "require": {
>     "smartins/passport-multiauth": "dev-fix-same-id-model-one-token",
> }
> ```
> 
> And run `composer update smartins/passport-multiauth`


thanks a lot @sfelix-martins. It fixed the issue

**Comment by sfelix-martins** [comment]
@codeilia Thanks brow

**Comment by pakcybershagufta** [comment]
Same issue i am facing laravel 5.7 and package 4.0 ?
Help required.
