### ISSUE TITLE
can't change expiration of token

### ISSUE THREAD

**Issue by JuanNitram** [sfelix-martins/passport-multiauth#76]
Hi, i have a problem with this. I add the next lines to AuthServiceProvider:

    Passport::tokensExpireIn(now()->addDays(15));

    Passport::refreshTokensExpireIn(now()->addDays(30));

This doesn't work, how can i change expiration time ?

Thanks.

**Comment by sfelix-martins** [comment]
Hi @JuanNitram , how are you generating the token? [Personal Access Tokens](https://github.com/sfelix-martins/passport-multiauth#personal-access-tokens) or accessing `oauth/token` route?

Remembering that the lifetime configurations don't works to `Personal Access Tokens` like explained on [Laravel Password docs](https://laravel.com/docs/5.7/passport#personal-access-tokens)
