### ISSUE TITLE
How to logout a user  who is haven token from your passport api

### ISSUE THREAD

**Issue by mdmusaib** [sfelix-martins/passport-multiauth#78]

**Comment by sfelix-martins** [comment]
@mdmusaib You can revoke tokens using the `revoke()` method from token instance. E.g.:

```php
$user->tokens()->each(function ($token) {
    echo $token->revoke();
});
```

The method `tokens()` from trait `SMartins\PassportMultiauth\HasMultiAuthApiTokens` provided by the package will return a `\Illuminate\Database\Eloquent\Collection` with `Laravel\Passport\Token` instances.

I hope it helps!
