### ISSUE TITLE
Issue with Accessing others data with token

### ISSUE THREAD

**Issue by mdmusaib** [sfelix-martins/passport-multiauth#79]
In my example project, I have three guard, users,partners,admins, but the thing is, If suppose i logged in a got a token of that particular user successfully, but the challenge with the same token I'm accessing other users? How to prevent this loop hole sir, I really need your help in this issue to fix asap

**Comment by sfelix-martins** [comment]
Please, check if it solve your problem https://github.com/sfelix-martins/passport-multiauth/issues/63#issuecomment-458506088

**Comment by sfelix-martins** [comment]
Duplicated https://github.com/sfelix-martins/passport-multiauth/issues/63#issuecomment-469140724
