### ISSUE TITLE
pass to other auth

### ISSUE THREAD

**Issue by soutarrr7** [sfelix-martins/passport-multiauth#8]
Thank you for make passport-multiauth.
It helps me a lot of works.

I can pass to take multi models.
but The problem is i can pass from both in auth:admin route.

If you have any solutions, i am appreciated let me know.

**Comment by sfelix-martins** [comment]
Hey @soutarrr7. I am not a native english speaker, so I had some trouble understanding your issue.

Can you check if the issue #5 is the same as yours and give me a feedback here? If it is not, can you put your issue in other words so I can try to understand again?

**Comment by soutarrr7** [comment]
Sorry!
It's same problem.
I didn't realize that update version of master branch.
And My english very noob so sorry.
Thank you for Answer.

**Comment by sfelix-martins** [comment]
Thank you @soutarrr7!  After test the master branch, can you give a feedback here? I am testing a bit before up a new release. If you can help me with this task...

**Comment by sfelix-martins** [comment]
The release [v1.0.0](https://github.com/sfelix-martins/passport-multiauth/releases/tag/v1.0.0) fix the problem with access tokens working with many models with same database id
