### ISSUE TITLE
Token issue with same id

### ISSUE THREAD

**Issue by pakcybershagufta** [sfelix-martins/passport-multiauth#80]
I am facing issue with token on get detail on user.If i add token of same id it get user based on id...BUG

**Comment by sfelix-martins** [comment]
Duplicated https://github.com/sfelix-martins/passport-multiauth/issues/63#issuecomment-469140724

**Comment by pakcybershagufta** [comment]
Done with help on Issue num 63.

Thanks

**Comment by pakcybershagufta** [comment]
'middleware' => 'multiauth:admin,user' is most imp
