### ISSUE TITLE
How to invoke the endpoint  /oauth/token

### ISSUE THREAD

**Issue by SachinBahukhandi** [sfelix-martins/passport-multiauth#83]
Hi there, I tried to invoke the enpoint  /oauth/token. But it leads to an error: 
`{"error":"invalid_client","message":"Client authentication failed"}`
Please guide me on how to invoke the /oauth/token. I used postman to invoke the endpoint using: 
         `{
   	    "email":"xyz@gmail.com",
	    "password":"sachin123",
            "grant_type" : "password",
            "client_id": "1",
            "client_secret" : "LGWZeh2nG0dclGsWBuC8wZsXV3RC1itXSD239R6Q",
            "provider" : "users"
         }`

**Comment by sfelix-martins** [comment]
You should use the grant client. Probably the registry with client_id = 2 generated by `passport:install` command.

**Comment by SachinBahukhandi** [comment]
you mean to use grant_type: client? Sorry I am not a professional on laravel and passport.

**Comment by SachinBahukhandi** [comment]
done works with:
    
    {
   	"username":"xyz@gmail.com",
	"password":"sachin123",
        "grant_type" : "password",
       "client_id": "2",
        "client_secret" : "rp7VkYpqvMwrZk73sDRB3RTFgaeMsHoRaHvHXlWD",
         "provider" : "users"
     }

**Comment by sfelix-martins** [comment]
@SachinBahukhandi very good. If you think that the docs should be more clearly, please send a pull request improving it.

Thanks!

**Comment by SachinBahukhandi** [comment]
Hi Samuel. I did not find any working implementation on how to register and login via admin or any other person except users.
Would be glad if I could find a working implementation of it. I cloned your repo but could not find it. Thank you.
