### ISSUE TITLE
The request is missing a required parameter

### ISSUE THREAD

**Issue by seyfeddineZig** [sfelix-martins/passport-multiauth#88]
Hi 
im getting a 500 response when i use your multi auth solution.
Here is the message :
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.

did any one get this ?

**Comment by itstrueimryan** [comment]
Probably not including the **providers** param, where you specify the provider, e..g `provider: admins`

**Comment by tumainimosha** [comment]
@seyfeddineZig refer to my reply on issue #89  [here](https://github.com/sfelix-martins/passport-multiauth/issues/89#issuecomment-496018193) to set a default provider provider and suppress this error.
