### ISSUE TITLE
actingAs cause 201, instead of 200

### ISSUE THREAD

**Issue by michaelnguyen2021** [sfelix-martins/passport-multiauth#92]
Please refer to this issue @ https://github.com/laravel/framework/pull/25873. The issue has been fixed in L5.7. I am using L5.8 and still have this issue, so my guess is it has to do with `passport-multiauth` plugin?

**Comment by sfelix-martins** [comment]
@michaelnguyen547 Are you using the `PassportMultiauth::actingAs()` like [docs](https://github.com/sfelix-martins/passport-multiauth#unit-tests) example?

**Comment by michaelnguyen2021** [comment]
yes I am

protected function signInAsUser($passenger = null)
{
$user = $user ?: factory('App\User')->create();
PassportMultiauth::actingAs($user);
return $user;
}

**Comment by michaelnguyen2021** [comment]
sorry to bother you, I can't get the v4.1.  I have `"smartins/passport-multiauth": "^4.0",` in `composer.json`, when I run `composer update `smartins/passport-multiauth`. it said `nothing to update`

**Comment by sfelix-martins** [comment]
@michaelnguyen547 Please, check it again. I updated on packagist.
