### ISSUE TITLE
got error after upgrading to 4.1

### ISSUE THREAD

**Issue by hosseinkarami-dev** [sfelix-martins/passport-multiauth#95]
hi. I have upgraded package but i got this error:
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Illuminate\Auth\Middleware\Authenticate::authenticate() must be of the type array, object given, called in C:\Shahrino\vendor\smartins\passport-multiauth\src\Http\Middleware\MultiAuthenticate.php on line 83 in file C:\Shahrino\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php on line 53

**Comment by sfelix-martins** [comment]
What's you laravel framework version? The version 4.1 of the package supports laravel framework >= 5.7.

**Comment by AhmadOf** [comment]
I have the same issue, My laravel version is 5.6 but it automatically install version 4.1 so after install version 4.0 I still get the same error, It seems that authenticate method take one parameter which is the guard array but you pass the request with guard like this:
$this->authenticate($request, $guard);

**Comment by hosseinkarami-dev** [comment]
> 
> 
> I have the same issue, My laravel version is 5.6 but it automatically install version 4.1 so after install version 4.0 I still get the same error, It seems that authenticate method take one parameter which is the guard array but you pass the request with guard like this:
> $this->authenticate($request, $guard);

I solved it but i no longer use this package. go to your composer.json and change laravel version to the latest(current is 5.8). be sure to upgrade your passport package to the latest version too. after that it will be ok again. but you should think of using one table instead. it is a better idea to use users table and for your multiple auth, make a role column or make tables related to users table. good luck!
